{{- with .Values.keycloak }}

apiVersion: v1
kind: Service

metadata:
  name: keycloak
  labels:
    app: keycloak

spec:
  type: NodePort

  ports:
  - name: keycloak-np
    port: {{ .listenPort }}
    targetPort: {{ .listenPort }}
    nodePort: {{ .nodePort }}

  selector:
    app: keycloak

{{- end }}
